name: Test
on : [push, pull_request]
jobs:
  set-up:
    runs-on: ubuntu-latest
    container: node:14.17.0-buster-slim

    services: 
      mongodb:
        image: mongo:4.4
        env:
          MONGO_INITDB_ROOT_USERNAME: a
          MONGO_INITDB_ROOT_PASSWORD: a
          MONGO_INITDB_DATABASE: myblog
        ports: 
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
      - name: Get dependencies
        run: yarn install --frozen-lockfile
      - name: test
        run: yarn test:ci
